import { Fragment, useEffect, useRef, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import {
  ArrowRight,
  ArrowUpRight,
  BookOpen,
  Brain,
  Check,
  Sparkles,
  TrendingUp,
} from 'lucide-react'
import { AppShell } from '@/components/app-shell'
import { Alert } from '@/components/ui/alert'
import { ScoreRing } from '@/components/charts'
import { Sparkline } from '@/components/charts'
import { Badge } from '@/components/ui/badge'
import { buttonVariants } from '@/components/ui/button'
import { DifficultyBadge, TypeBadge } from '@/components/interview-ui'
import { api } from '@/lib/api'
import { downloadPdf } from '@/lib/pdf-export'
import { fmtDate, fmtMinutes } from '@/lib/format'
import type { InterviewReport, SignalTone } from '@/lib/types'
import { cn } from '@/lib/utils'
import {
  DetailSkeleton,
  interviewDisplayTitle,
  InterviewHeader,
  InterviewNotFound,
  useInterview,
} from './shared'

const SIGNAL_BADGE: Record<SignalTone, 'strong' | 'good' | 'vague' | 'weak'> = {
  strong: 'strong',
  good: 'good',
  vague: 'vague',
  weak: 'weak',
}

export function InterviewReportPage() {
  const { id } = useParams()
  const [searchParams] = useSearchParams()
  const exportMode = searchParams.get('export')
  const fullExport = exportMode === 'full'
  const exportStarted = useRef(false)
  const { interview, loading, error: interviewError } = useInterview(id)
  const [report, setReport] = useState<InterviewReport | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [fullData, setFullData] = useState<{ metrics: { overall: number; questionScores: { label: string; value: number }[]; activeSeconds: number }; history: { label: string; detail: string; at: string }[] } | null>(null)

  useEffect(() => {
    if (!id) return
    let alive = true
    api
      .getReport(id)
      .then((r) => {
        if (alive) setReport(r)
      })
      .catch(() => {
        if (alive) setError('Unable to load interview report.')
      })
    return () => {
      alive = false
    }
  }, [id])

  useEffect(() => {
    if (!id || !fullExport) return
    Promise.all([api.getMetrics(id), api.getHistory(id)]).then(([metrics, history]) => setFullData({ metrics: metrics as { overall: number; questionScores: { label: string; value: number }[]; activeSeconds: number }, history })).catch(() => setFullData({ metrics: { overall: 0, questionScores: [], activeSeconds: 0 }, history: [] }))
  }, [id, fullExport])

  useEffect(() => {
    if (!fullExport || !report || !fullData || exportStarted.current) return
    exportStarted.current = true
    const frame = window.requestAnimationFrame(() => {
      const root = document.querySelector<HTMLElement>('.report-print-root')
      if (root) void downloadPdf(root, `${interview?.roleTitle ?? 'interview'} full report`).finally(() => window.close())
    })
    return () => window.cancelAnimationFrame(frame)
  }, [report, fullExport, fullData, interview?.roleTitle])

  if (loading || (!report && interview?.status === 'COMPLETED')) {
    return (
      <AppShell title="Interview Report">
        <DetailSkeleton />
      </AppShell>
    )
  }
  if (interviewError || error) {
    return <AppShell title="Interview Report"><Alert variant="destructive">{interviewError ?? error}</Alert></AppShell>
  }
  if (!interview || !report) {
    return (
      <AppShell title="Interview Report">
        <InterviewNotFound />
      </AppShell>
    )
  }

  // Reports generated by older deployments may lack optional presentation
  // arrays. The aggregate score remains useful, so render empty sections
  // rather than letting a missing array crash the whole route.
  const categoryScores = report.categoryScores ?? []
  const difficultyProgression = report.difficultyProgression ?? []
  const strengths = (report.strengths ?? []).slice(0, 12)
  const weaknesses = (report.weaknesses ?? []).slice(0, 7)
  const recommendations = (report.recommendations ?? []).slice(0, 7)
  const questions = report.questions ?? []
  const summaryPoints = report.summary.split(/(?<=[.!?])\s+/).filter(Boolean).slice(0, 4)

  return (
    <AppShell title="Interview Report">
      <div className="interview-print-root report-print-root animate-slide-up mx-auto flex max-w-5xl flex-col gap-5">
        <InterviewHeader interview={interview} active="report" />
        <div className="print-document-title">
          <h1>{interviewDisplayTitle(interview)} — Interview Report</h1>
          <p>{interview.company ?? 'No target company'} · {interview.domain} · {fmtDate(interview.createdAt)}</p>
        </div>

        {fullExport ? <section className="full-export-overview rounded-2xl border border-border bg-card p-6"><h2 className="text-lg font-semibold">Overview</h2><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-muted-foreground">Role</dt><dd>{interview.roleTitle}</dd></div><div><dt className="text-muted-foreground">Session time</dt><dd>{fullData ? `${Math.floor(fullData.metrics.activeSeconds / 60)}m ${fullData.metrics.activeSeconds % 60}s` : '—'}</dd></div><div><dt className="text-muted-foreground">Questions answered</dt><dd>{fullData?.metrics.questionScores.length ?? 0}</dd></div><div><dt className="text-muted-foreground">Completion</dt><dd>100%</dd></div></dl></section> : null}

        {fullExport && fullData ? <section className="full-export-metrics rounded-2xl border border-border bg-card p-6"><h2 className="text-lg font-semibold">Metrics</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><div><p className="text-xs text-muted-foreground">Overall score</p><p className="text-xl font-semibold">{fullData.metrics.overall}</p></div>{fullData.metrics.questionScores.map((score) => <div key={score.label}><p className="text-xs text-muted-foreground">{score.label}</p><p className="text-xl font-semibold">{score.value}/100</p></div>)}</div></section> : null}

        {/* hero */}
        <section className="rounded-2xl border border-primary/25 bg-primary/5 p-6 sm:p-7">
          <div className="flex flex-wrap items-center gap-6">
            <ScoreRing value={report.overallScore} size={124} stroke={10} />
            <div className="min-w-0 flex-1">
              <div className="flex flex-wrap items-center gap-2">
                <TypeBadge type={interview.type} />
                <DifficultyBadge difficulty={interview.difficulty} />
                <Badge variant="strong" dot>
                  Completed
                </Badge>
              </div>
              <h2 className="mt-2.5 text-xl font-semibold tracking-tight sm:text-2xl">
                Interview Report
              </h2>
              <p className="mt-1 font-mono text-[11px] text-muted-foreground">
                {interview.company} · {fmtDate(interview.createdAt)} ·{' '}
                {fmtMinutes(interview.durationMin)} · {interview.rounds} rounds
              </p>
              <ul className="mt-3 grid max-w-2xl gap-1.5 text-sm leading-relaxed text-muted-foreground">
                {summaryPoints.map((point) => <li key={point} className="flex gap-2"><span className="text-primary">•</span><span>{point}</span></li>)}
              </ul>
            </div>
          </div>
        </section>

        {/* categories + adaptive journey */}
        <div className="grid gap-4 lg:grid-cols-2">
          <section className="rounded-2xl border border-border bg-card p-6">
            <h2 className="text-sm font-semibold">Category performance</h2>
            <div className="mt-4 flex flex-col gap-4">
              {categoryScores.map((c) => (
                <div key={c.label}>
                  <div className="mb-1.5 flex items-center justify-between text-sm">
                    <span>{c.label}</span>
                    <span className="font-mono tabular-nums text-muted-foreground">
                      {c.value}%
                    </span>
                  </div>
                  <div className="h-2 overflow-hidden rounded-full bg-secondary">
                    <div
                      className="h-full rounded-full bg-primary"
                      style={{ width: `${c.value}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </section>

          <section className="rounded-2xl border border-border bg-card p-6">
            <div className="flex items-center gap-2">
              <TrendingUp className="size-4 text-primary" />
              <h2 className="text-sm font-semibold">Adaptive journey</h2>
            </div>
            {interview.difficulty === 'Adaptive' && difficultyProgression.length ? <>
              <Sparkline values={difficultyProgression.map(difficultyValue)} height={92} className="mt-4" />
              <div className="mt-3 flex flex-wrap items-center gap-2">
              {difficultyProgression.map((step, i) => (
                <Fragment key={`${step}-${i}`}>
                  {i > 0 ? <ArrowRight className="size-3 shrink-0 text-muted-foreground" /> : null}
                  <span
                    className={cn(
                      'rounded-md px-2.5 py-1 font-mono text-[10px] uppercase tracking-wider ring-1',
                      journeyChipCls(step),
                    )}
                  >
                    {step}
                  </span>
                </Fragment>
              ))}
              </div>
              <p className="mt-3 font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Difficulty by answered question</p>
            </> : <p className="mt-4 text-sm leading-relaxed text-muted-foreground">This interview used a fixed difficulty, so there is no adaptive journey to display.</p>}
          </section>
        </div>

        {/* strengths / weaknesses */}
        <div className="grid gap-4 lg:grid-cols-2">
          <section className="rounded-2xl border border-border bg-card p-6">
            <h2 className="text-sm font-semibold text-[var(--signal-strong)]">Strengths</h2>
            <ul className="mt-3 flex flex-col gap-2.5">
              {strengths.map((s) => (
                <li key={s} className="flex items-start gap-2.5 text-sm">
                  <Check className="mt-0.5 size-3.5 shrink-0 text-[var(--signal-strong)]" strokeWidth={3} />
                  {s}
                </li>
              ))}
            </ul>
          </section>
          <section className="rounded-2xl border border-border bg-card p-6">
            <h2 className="text-sm font-semibold text-[var(--signal-vague)]">Areas to improve</h2>
            <ul className="mt-3 flex flex-col gap-2.5">
              {weaknesses.map((w) => (
                <li key={w} className="flex items-start gap-2.5 text-sm">
                  <ArrowUpRight className="mt-0.5 size-3.5 shrink-0 text-[var(--signal-vague)]" />
                  {w}
                </li>
              ))}
            </ul>
          </section>
        </div>

        {/* recommendations (FR-29) */}
        <section className="rounded-2xl border border-border bg-card p-6">
          <div className="flex flex-wrap items-center gap-2">
            <BookOpen className="size-4 text-primary" />
            <h2 className="text-sm font-semibold">Recommended resources</h2>
            <span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
              tied to observed gaps
            </span>
          </div>
          <ul className="mt-3 flex flex-col divide-y divide-border">
            {recommendations.map((r) => (
              <li
                key={r.gap}
                className="flex flex-col gap-1.5 py-3 first:pt-0 last:pb-0 sm:flex-row sm:items-center sm:gap-4"
              >
                <span className="shrink-0 self-start rounded-md bg-[var(--signal-vague)]/10 px-2.5 py-1 font-mono text-[10px] uppercase tracking-wider text-[var(--signal-vague)] ring-1 ring-[var(--signal-vague)]/25 sm:self-auto">
                  {r.gap}
                </span>
                <span className="text-sm leading-relaxed text-muted-foreground">{r.resource}</span>
              </li>
            ))}
          </ul>
        </section>

        {/* question-level analysis */}
        <div className="flex items-center justify-between">
          <h2 className="text-sm font-semibold">Question-level analysis</h2>
          <span className="font-mono text-[11px] text-muted-foreground">
            {questions.length} questions
          </span>
        </div>
        <div className="flex flex-col gap-4">
          {questions.map((q, i) => (
            <details key={i} className="group rounded-2xl border border-border bg-card">
              <summary className="flex cursor-pointer list-none flex-wrap items-center justify-between gap-3 p-5 [&::-webkit-details-marker]:hidden">
                <div className="flex flex-wrap items-center gap-2">
                  <Badge variant="neutral">Q{i + 1}</Badge>
                  <Badge variant="outline">{q.level}</Badge>
                  <Badge variant={SIGNAL_BADGE[q.evaluation.signal]} dot>
                    {q.evaluation.signal}
                  </Badge>
                </div>
                <h3 className="min-w-0 flex-1 text-sm font-semibold leading-relaxed sm:px-2">{q.question}</h3>
                <span className={cn('rounded-full px-3 py-1 font-mono text-sm font-semibold tabular-nums ring-1', scoreClass(q.evaluation.score))}>
                  {q.evaluation.score}
                  <span className="text-muted-foreground">/100</span>
                </span>
              </summary>

              <div className="border-t border-border p-5 pt-4">
              <h3 className="text-sm font-semibold leading-relaxed">{q.question}</h3>

              <div className="mt-3 rounded-lg border border-border bg-background/50 px-3.5 py-2.5">
                <p className="font-mono text-[9px] uppercase tracking-wider text-muted-foreground">
                  Your answer
                </p>
                <p className="mt-1 text-sm leading-relaxed">{q.answer}</p>
              </div>

              <div className="mt-3 flex items-start gap-2.5 rounded-lg bg-primary/5 px-3.5 py-2.5 ring-1 ring-primary/20">
                <Brain className="mt-0.5 size-3.5 shrink-0 text-primary" />
                <div className="min-w-0">
                  <p className="font-mono text-[9px] uppercase tracking-wider text-primary">
                    AI evaluation
                  </p>
                  <p className="mt-1 text-sm leading-relaxed">{q.evaluation.feedback}</p>
                </div>
              </div>

              {q.evaluation.strengths.length > 0 || q.evaluation.weaknesses.length > 0 ? (
                <div className="mt-3 grid gap-3 sm:grid-cols-2">
                  {q.evaluation.strengths.length > 0 ? (
                    <div className="rounded-lg border border-border bg-background/50 px-3.5 py-2.5">
                      <p className="font-mono text-[9px] uppercase tracking-wider text-[var(--signal-strong)]">
                        Strengths
                      </p>
                      <ul className="mt-1.5 flex flex-col gap-1.5">
                        {q.evaluation.strengths.slice(0, 4).map((s) => (
                          <li key={s} className="flex items-start gap-1.5 text-xs leading-relaxed">
                            <Check className="mt-0.5 size-3 shrink-0 text-[var(--signal-strong)]" strokeWidth={3} />
                            {s}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ) : null}
                  {q.evaluation.weaknesses.length > 0 ? (
                    <div className="rounded-lg border border-border bg-background/50 px-3.5 py-2.5">
                      <p className="font-mono text-[9px] uppercase tracking-wider text-[var(--signal-vague)]">
                        Needs work
                      </p>
                      <ul className="mt-1.5 flex flex-col gap-1.5">
                        {q.evaluation.weaknesses.slice(0, 4).map((w) => (
                          <li key={w} className="flex items-start gap-1.5 text-xs leading-relaxed">
                            <ArrowUpRight className="mt-0.5 size-3 shrink-0 text-[var(--signal-vague)]" />
                            {w}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ) : null}
                </div>
              ) : null}

              {q.evaluation.improvedAnswer ? (
                <div className="mt-3 flex items-start gap-2.5 rounded-lg bg-[var(--signal-strong)]/5 px-3.5 py-2.5 ring-1 ring-[var(--signal-strong)]/25">
                  <Sparkles className="mt-0.5 size-3.5 shrink-0 text-[var(--signal-strong)]" />
                  <div className="min-w-0">
                    <p className="font-mono text-[9px] uppercase tracking-wider text-[var(--signal-strong)]">
                      Improved answer
                    </p>
                    <p className="mt-1 text-sm leading-relaxed">{q.evaluation.improvedAnswer}</p>
                  </div>
                </div>
              ) : null}
              </div>
            </details>
          ))}
        </div>

        {/* footer actions */}
        <div className="report-footer flex flex-wrap justify-center gap-2 pt-2">
          <Link to="/interviews/new" className={cn(buttonVariants())}>
            Practice again
          </Link>
          <Link to="/dashboard" className={cn(buttonVariants({ variant: 'outline' }))}>
            Back to dashboard
          </Link>
        </div>

        {fullExport && fullData ? <section className="full-export-history rounded-2xl border border-border bg-card p-6"><h2 className="text-lg font-semibold">History</h2><ol className="mt-4 space-y-3">{fullData.history.map((event) => <li key={`${event.label}-${event.at}`}><p className="font-medium text-sm">{event.label}</p><p className="text-sm text-muted-foreground">{event.detail}</p></li>)}</ol></section> : null}
      </div>
    </AppShell>
  )
}

function scoreClass(score: number) {
  if (score >= 80) return 'bg-[var(--signal-strong)]/10 text-[var(--signal-strong)] ring-[var(--signal-strong)]/30'
  if (score >= 60) return 'bg-primary/10 text-primary ring-primary/30'
  if (score >= 40) return 'bg-[var(--signal-vague)]/10 text-[var(--signal-vague)] ring-[var(--signal-vague)]/30'
  return 'bg-[var(--signal-weak)]/10 text-[var(--signal-weak)] ring-[var(--signal-weak)]/30'
}

function difficultyValue(value: string) {
  if (value === 'HARD') return 3
  if (value === 'MEDIUM') return 2
  return 1
}

function journeyChipCls(step: string) {
  const s = step.toLowerCase()
  if (s.includes('follow-up'))
    return 'bg-[var(--signal-vague)]/10 text-[var(--signal-vague)] ring-[var(--signal-vague)]/30'
  if (s.includes('hard') || s.includes('raised'))
    return 'bg-[var(--signal-weak)]/10 text-[var(--signal-weak)] ring-[var(--signal-weak)]/30'
  if (s.includes('easy'))
    return 'bg-[var(--signal-strong)]/10 text-[var(--signal-strong)] ring-[var(--signal-strong)]/30'
  return 'bg-primary/10 text-primary ring-primary/25'
}
